// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nduiocjjwlkeowrjohxb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5kdWlvY2pqd2xrZW93cmpvaHhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1NzU2MjMsImV4cCI6MjA3MzE1MTYyM30.WCvu-rt3lip4Idw8T3rozk6Ukt0mh6z31r6LM-sAUwI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});